const players = {
  player1: {
    name: "Christian252010",
    skin: "skin/cris.png",
    discord: "christianjuniadi",
    rank: "Mythic",
    role: "Builder",
    timezone: "WIB",
    free: "Malam",
    hobby: "Turu",
    cita: "Orang Sukses",
    about: "Dingin Tetapi Tidak Kejam",
    moto: "Menyerah Bukanlah Pilihan",
    isSlim: true
  },
  player2: {
    name: "Elrumi19",
    skin: "skin/elrum.png",
    discord: "eroitina",
    rank: "Mythic",
    role: "Grinder",
    timezone: "WIT",
    free: "Setiap Hari",
    hobby: "Ngocok",
    cita: "Biduan",
    about: "Saya adalah raja ibelis",
    moto: "Hidup seperti Lery",
    isSlim: true
  },
  player3: {
    name: "frexymax",
    skin: "skin/prex.png",
    discord: "frexyy0166",
    rank: "Mythic",
    role: "Builder",
    timezone: "Pluto",
    free: "Selalu ada",
    hobby: "Mancing",
    cita: "Presiden",
    about: "Yo ndak tau kok tanya saya",
    moto: "Buly elrumi setiap hari",
    isSlim: true
  },
  player4: {
    name: "AsaaNiBozz",
    skin: "skin/asaa.png",
    discord: "mocha_hasya",
    rank: "Legend",
    role: "Builder",
    timezone: "WIB",
    free: "Kapan-Kapan",
    hobby: "Bernafas",
    cita: "LC",
    about: "Hanya manusia biasa",
    moto: "Jangan lupa bernafas",
    isSlim: true
  },
  player5: {
    name: "GyzzaFaril20",
    skin: "skin/aril.png",
    discord: "gyzzafaril",
    rank: "Mythic",
    role: "Grinder",
    timezone: "WIB",
    free: "Weekend-Malam",
    hobby: "Catur",
    cita: " Desain grafis",
    moto: "It's the one and only G Y double Z",
    about: "Teknisi Redstone yang berorientasi pada efisiensi dengan keahlian ganda dalam optimalisasi ekonomi Villager. Berpengalaman dalam merancang dan mengeksekusi sistem otomatisasi skala besar yang resource-friendly dan server-friendly (minim lag). Memiliki pemahaman mendalam tentang mekanika inti permainan (game mechanics) untuk menemukan solusi inovatif. Spesialis dalam mengubah sirkuit yang rumit menjadi desain yang ringkas dan andal. Terbukti berhasil membangun infrastruktur trading hall yang mampu mengamankan penawaran dagang (trade) paling berharga dengan diskon maksimum. Terampil dalam troubleshooting sirkuit yang ada dan siap menerapkan otomatisasi penuh untuk mencapai kemandirian sumber daya.",
    isSlim: false
  },
  player6: {
    name: "setya_315104",
    skin: "skin/setya.png",
    discord: "setya031",
    rank: "Legend",
    role: "Grinder",
    timezone: "WIB",
    free: "malam",
    hobby: "Fishing and reading a novel",
    cita: "Bartender",
    moto: "Stay true to yourself",
    about: "I am a mighty person",
    isSlim: false
  },
  player7: {
    name: "Ponkzz_x_C",
    skin: "skin/ponk.png",
    discord: "ponkkzzz",
    rank: "Rakyat",
    role: "Grinder",
    timezone: "WIB",
    free: "MALAM",
    hobby: "Basket😋",
    cita: "ke jepang🙏",
    moto: "GTW",
    about: "aku manusia, kalo kau apa, ga boleh sama",
    isSlim: false
  },
  player8: {
    name: "ReinyArthana ",
    skin: "skin/rein.png",
    discord: "reiny27 ",
    rank: "Legend",
    role: "Grinder",
    timezone: "WIB",
    free: "Malam",
    hobby: "Eksperimen makanan ",
    cita: "Nikahin Arion ",
    moto: "Pengen tinggi ",
    about: "Suka makan ",
    isSlim: false
  },
  player9: {
    name: "Rafz5381",
    skin: "skin/steve.png",
    discord: "Fearman._",
    rank: "Legend",
    role: "Builder",
    timezone: "WIB",
    free: "Hari libur",
    hobby: "Main takraw",
    cita: "Jadi pemadam kebakaran",
    moto: "Bernafas manual terkadang tidak buruk itu mengingatkan kita pada siapa yg menciptakan kita.",
    about: "Suka kepanasan ,kipas gua rusak tolong, gua perbaiki bang",
    isSlim: false
  },
  player10: {
    name: "AGUNG_TURU2402",
    skin: "skin/agung.png",
    discord: "agung_turu",
    rank: "Master",
    role: "Grinder",
    timezone: "WIB",
    free: "Tergantung",
    hobby: "Main Game",
    cita: "Ultramen (belum ada) ",
    moto: "Season depan pasti imortal",
    about: "GANTENG ABIS",
    isSlim: false
  },
  player11: {
    name: "Mufit166383698",
    skin: "skin/mufit.png",
    discord: "Mufit10635",
    rank: "Master",
    role: "Grinder",
    timezone: "WIB",
    free: "Malam kalau lagi gabut",
    hobby: "Membuat kerajinan ",
    cita: "Menjadi YouTuber ",
    moto: "Gabut gabutt gabut",
    about: "Seseorang yang ganteng ",
    isSlim: false
  },
  player12: {
    name: "Bayu_Alif7693",
    skin: "skin/steve.png",
    discord: "bayu_alif",
    rank: "Master",
    role: "Builder",
    timezone: "WIB",
    free: "Sore jam 3 sampai jam 5an",
    hobby: "Gatau/Gaada",
    cita: "Masuk surga",
    moto: "Bersatu kita teguh, berperang kita runtuh",
    about: "Gw orang nya agak sok asik",
    isSlim: false
  },
  player13: {
    name: "nareys15",
    skin: "skin/narey.png",
    discord: "nnaresyh",
    rank: "Legend",
    role: "Grinder",
    timezone: "WIB",
    free: "sore, malam",
    hobby: "cooking ",
    cita: "jdi org terkaya sedunia 💀🤤",
    moto: "gaada moto yg penting hidup sehat dan banya uang",
    about: "Akulah jawir imupt",
    isSlim: false
  },
  player14: {
    name: "Undercocoo",
    skin: "skin/under.png",
    discord: "undercoco_mc",
    rank: "Rakyat",
    role: "Builder",
    timezone: "WIB",
    free: "Sore sampai malam",
    hobby: "Maen roblox dan minecraft",
    cita: "Jadi developer 🗿",
    moto: "gk ada 🗿",
    about: "Males",
    isSlim: false
  }
};